### PR TITLE
Create Footer Component.

### PR DESCRIPTION
**Pull request by abrugal**
Creates Footer Component.

Has a home icon, heart, search and person, just like the figma.

### CODE REVIEW

**Comment by TylerMathis** [comment]
Design wise this is awesome, but I think we might want to implement with the bottom tab navigator that is already used (integrated with react-navigation) instead of a new component. I'll take a look and grab some links when I get home.

Thanks for working on this!

**Comment by abrugal** [comment]
Yup after looking at your code again I see you used that bottom tab navigator, which is way easier lol, I'll implement that

**Comment by TylerMathis** [comment]
Awesome, you da best

**Comment by abrugal** [comment]
## Describe your changes
Create footer that includes all of our tabs.

## Issue ticket number and link
#22 

## Checklist before requesting a review
- [x] All code is linted and conforms to style guide
- [x] All necessary context is described in the PR or Issue
- [x] This branch is code and feature complete. If it is not complete, this PR is a draft.

**Comment by abrugal** [comment]
New footer 
Screenshot_20221202-235008_Expo Go

**Comment by TylerMathis** [comment]
Yessir!!! Lets goooooo this is exactly what we're looking for. Beautiful stuff, lgtm!

**Review by TylerMathis — APPROVED** [review]

**Pull request merged**
