### PR TITLE
Implement all the sending things

### LINKED ISSUE #174: Users can rate a route they've just sent
A popup asking for optional 5-star rating

### LINKED ISSUE #175: Users can choose to share a send on a route
This makes a mini post to the route automatically

### PR DESCRIPTION
**Pull request by JakeSteinebronn**
# Changes

# Issue ticket number and link
closes #175 
closes #174

### CODE REVIEW

**Review by tylerhm — COMMENTED** [review]
This is awesome! Should we include the name of the route in the mini post?

**Comment by JakeSteinebronn** [comment]
I included the name of the route in the mini post; it's not a link because I intend to make route linking not cost a read :p

**Comment by tylerhm** [comment]
I tested locally and sent a new route. The route name didn't show up when viewing the post on my profile.

**Comment by tylerhm** [comment]
image

**Comment by JakeSteinebronn** [comment]
Evidently the routeInfo isn't getting set when a new post is created, i'll look into that

**Comment by JakeSteinebronn** [comment]
Fixed:
image

**Review by tylerhm — APPROVED** [review]
sweet 👍🏼

**Pull request merged**
