### PR TITLE
Update Follows and UserRow UI

### PR DESCRIPTION
**Pull request by JakeSteinebronn**
# Changes
- Switch back to using UserRow in the follows list
- Add display for whether you are following / followed by this user in the user row (shows up in search as well)
- Add search bar in follows screen
- Add option in follows screen for both following + followers
- Use a select instead of buttons for cleaner UI
image

This is a UX/UI PR  so it also acts as discussion

# Issue ticket number and link

### CODE REVIEW

**Comment by tylerhm** [comment]
Instead of displaying both "Follows you" and "Following" for their union how about we do a different message all together like "Friends" or something similar.

**Comment by JakeSteinebronn** [comment]
Is that universally intuitive? I'd probably be confused if I saw that and think "oh what's the difference between friends and followers?" But if it's just me then let's send it on friends

**Comment by tylerhm** [comment]
> Is that universally intuitive? I'd probably be confused if I saw that and think "oh what's the difference between friends and followers?" But if it's just me then let's send it on friends

Yeah it's tough to find wording that would make sense universally, the spacing just looks super off right now. When there are multiple context indicators like this, it is important that they not only have their own wording but their own *location*. This makes it much easier for a user to understand what they mean at a glance. I suggested a completely different word to indicate union as it would remove this requirement, but we can always just put them in distinct locations if we can't find a strong word that represents both.

**Comment by JakeSteinebronn** [comment]
@tylerhm Updated; as per your suggestion, I fixed the positions of the indicators regardless of the number of them. I did this instead of introducing another term for the users to deduce

**Review by tylerhm — APPROVED** [review]
Nice! Thanks for addressing feedback

**Pull request merged**
