### PR TITLE
Update regex to new spec

### LINKED ISSUE #87: Update Register field verification
When creating a new account, we are now limiting the registration fields to the following restrictions.

```yaml
email: valid email format
username: 5 <= len <= 15, lowercase a-z
displayName: 5 <= len <= 30, lower/uppercase and spaces
password: len >= 8
```

### PR DESCRIPTION
**Pull request by TylerMathis**
# Changes
Update the regex matchers to adhere to new spec in linked issue.

# Issue ticket number and link
closes #87

### CODE REVIEW

**Comment by JakeSteinebronn** [comment]
Once landed, I'm exporting `validUsername` and `validDisplayname`. For the sake of removing code duplication, what do you think about using those instead?

**Comment by TylerMathis** [comment]
That's perfect! I'll leave this PR open and drop a migration commit on top once your code has landed.

**Comment by TylerMathis** [comment]
I've just updated the function calls to your API. Since xplat is now bumped, this must be merged *after* #86

**Review by abrugal — APPROVED** [review]
LGTM

**Pull request merged**
