### PR TITLE
Add component prop support, build RouteRow

### PR DESCRIPTION
**Pull request by TylerMathis**
## Props
Props are a critical part of building functional React projects, and since we are using TypeScript there is a bit of overhead to get them set up in a route enabled environment. The [React Navigation TypeScript Docs](https://reactnavigation.org/docs/typescript/) were very helpful getting this up and running.

## RouteRow
As specified in our [Routes Figma](https://www.figma.com/file/MjlTrOoFwO50FxJrQbd70K/Climbing-App----Prototypes?node-id=58%3A3734&t=12VKmZ7cMlppHAJB-0), we need a row that can represent a route in a scroll view. This component builds out this functionality.

| RouteRow with test data |
| - |
| image |

### CODE REVIEW

**Comment by TylerMathis** [comment]
Closed old PR to fast-forward onto `main`

**Comment by Henry-Graves** [comment]
looks solid, good work

**Review by Henry-Graves — APPROVED** [review]
looks extra solid, extra good work

**Review by abrugal — COMMENTED** [review]
What do the sandbox names and routes signify? I know default is obviously default but what does sandbox mean, cause when I hear sandbox I think of a testing environment

**Comment by TylerMathis** [comment]
@abrugal you are 100% correct that the `Sandbox` is a testing environment. The `Sandbox` is a tab that simply lists out all of our components and allows the user to click on them to see a testing version. Will help with individual component debugging down the line. This tab will not be rendered for production builds.

**Comment by TylerMathis** [comment]
https://user-images.githubusercontent.com/36250052/201566773-17cb4f9b-f2a0-4644-9259-5a670b7d5001.MOV

Example of what viewing a component in the Sandbox looks like.

**Comment by TylerMathis** [comment]
> What do the sandbox names and routes signify?
The Sandbox names are names of the components, routes are the actual routing logic to navigate to each.

**Comment by abrugal** [comment]
@TylerMathis Thanks for the explanation!

**Review by abrugal — APPROVED** [review]
LGTM

**Pull request merged**
