### PR TITLE
Profile create post entrypoint

### LINKED ISSUE #217: Create post entry point in profile

### PR DESCRIPTION
**Pull request by abrugal**
# Changes

User's profile now has a button with multiple options, which includes creating a post.

https://user-images.githubusercontent.com/5271307/219877224-6af57d9f-3971-4757-9ada-cca131eeee4f.mp4

# Issue ticket number and link
Closes #217

### CODE REVIEW

**Comment by tylerhm** [comment]
This is super cool! What are your thoughts on including it in the context menu that is already provided on profiles instead of via a button in the center?

**Comment by JakeSteinebronn** [comment]
+1 to adding these actions to the user context menu

**Comment by abrugal** [comment]
Which context menu?

**Comment by tylerhm** [comment]
> Which context menu?

The one [constructed](https://github.com/ucf-tower-app/mobile/blob/02ea03fd8043a482dbb1153ff441924ac3eedd2b/screens/profile/Profile.tsx#L70-L80) in the profile.

**Comment by abrugal** [comment]
DIdn't realize that existed. Do we plan on leaving it as a three dot menu? I feel like it looks goofy having two 3 dot menus right on top of each other

**Comment by tylerhm** [comment]
> DIdn't realize that existed. Do we plan on leaving it as a three dot menu? I feel like it looks goofy having two 3 dot menus right on top of each other

could always rotate the dots the other direction. I'm not sure if there is an icon that is equally as descriptive for what it does.

**Review by tylerhm — APPROVED** [review]
Poggies

**Pull request merged**
